### ISSUE TITLE
Nome estranho

### ISSUE THREAD

**Issue by DavidGomesh** [TadeuViegas/Aula01#2]
# Problema no while

https://github.com/TadeuViegas/Aula01/blob/1aca06cc1a7d251d2a258390efd4b3bf6a0cc26f/main.c#L11

Seria melhor mudar o nome da variável!

Sugestão:
```c
}while(opcao != 0);
```

**Comment by TadeuViegas** [comment]
Não quero mudar!

**Comment by DavidGomesh** [comment]
Mudae siow... Coé....

**Comment by TadeuViegas** [comment]
Ta okay.

**Comment by DavidGomesh** [comment]
Escrevi
